# Baixando a imagem
From apache/airflow:2.10.2
# adicionar o arquiivo com as dependencies
ADD requirements.txt .
# Executar pip install
RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt